backend:
  name: git-gateway
  branch: netlify # Branch to update (optional; defaults to master)

local_backend: true

media_folder: static/img
public_folder: /img

collections:
  - name: 'articles'
    label: 'Articles'
    label_singular: 'Article'
    folder: 'content/articles'
    format: 'frontmatter'
    sort: 'date:desc'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Hero', name: 'hero', allow_multiple: false, widget: 'image' }
      - { label: 'Publish Date', name: 'date', widget: 'date', format: 'Do MMMM YYYY' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Meta Description', name: 'meta_description', widget: 'string'}
      - {
        label: 'Content Blocks',
        label_singular: 'Content Block',
        name: 'contentBlocks',
        widget: 'list',
        min: 1,
        fields: [
          {
            label: 'Images', 
            label_singular: 'Image', 
            name: 'images', 
            allow_multiple: true, 
            required: false,
            widget: 'list', 
            fields: [
              { 
                label: 'Image', 
                name: 'src', 
                required: true,
                widget: 'image'
              },
              { label: 'Caption', name: 'caption', type: 'String', required: true}
            ]
          },
          { label: 'Content', name: 'content', widget: 'markdown', required: false, },
          { name: 'youtube', label: 'YouTube Embed Code', widget: 'text', required: false }
        ]
      }
      - { label: 'Tags',
          name: 'tags',
          widget: 'relation',
          collection: 'tags',
          folder: 'content/_tags/',
          display_fields: [title],
          search_fields: [title],
          value_field: 'title',
          multiple: true
        }
  - name: 'caseStudies'
    label: 'Case Studies'
    label_singular: 'Case Study'
    folder: 'content/case-studies'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Hero', name: 'hero', allow_multiple: false, widget: 'image' }
      - { label: 'Category', name: 'category', widget: 'string'}
      - { label: 'Year', name: 'year', widget: 'number', default: '2022' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Meta Description', name: 'meta_description', widget: 'string'}
      - { label: 'Summary', name: 'summary', widget: 'markdown' }
      - {
        label: 'Images', 
        label_singular: 'Image', 
        name: 'summaryImages', 
        allow_multiple: true, 
        required: false,
        widget: 'list', 
        fields: [
          { 
            label: 'Image', 
            name: 'src', 
            required: true,
            widget: 'image'
          },
          { label: 'Caption', name: 'caption', type: 'String', required: true}
        ]
      }
      - { label: 'Background', name: 'background', widget: 'markdown', required: false }
      - {
        label: 'Images', 
        label_singular: 'Image', 
        name: 'backgroundImages', 
        allow_multiple: true, 
        required: false,
        widget: 'list', 
        fields: [
          { 
            label: 'Image', 
            name: 'src', 
            required: true,
            widget: 'image'
          },
          { label: 'Caption', name: 'caption', type: 'String', required: true}
        ]
      }
      - { label: 'Goals', name: 'goals', widget: 'markdown', required: false }
      - {
        label: 'Images', 
        label_singular: 'Image', 
        name: 'goalsImages', 
        allow_multiple: true, 
        required: false,
        widget: 'list', 
        fields: [
          { 
            label: 'Image', 
            name: 'src', 
            required: true,
            widget: 'image'
          },
          { label: 'Caption', name: 'caption', type: 'String', required: true}
        ]
      }
      - { label: 'Method', name: 'method', widget: 'markdown', required: false }
      - {
        label: 'Images', 
        label_singular: 'Image', 
        name: 'methodImages', 
        allow_multiple: true, 
        required: false,
        widget: 'list', 
        fields: [
          { 
            label: 'Image', 
            name: 'src', 
            required: true,
            widget: 'image'
          },
          { label: 'Caption', name: 'caption', type: 'String', required: true}
        ]
      }
      - { label: 'Results', name: 'results', widget: 'markdown', required: false }
      - {
        label: 'Images', 
        label_singular: 'Image', 
        name: 'resultsImages', 
        allow_multiple: true, 
        required: false,
        widget: 'list', 
        fields: [
          { 
            label: 'Image', 
            name: 'src', 
            required: true,
            widget: 'image'
          },
          { label: 'Caption', name: 'caption', type: 'String', required: true}
        ]
      }
      - { label: 'Wrap Up', name: 'wrap-up', widget: 'markdown', required: false }
  - name: 'tags'
    label: 'Tags'
    label_singular: 'Tag'
    folder: 'content/tags/'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { 
          label: 'Title', 
          name: 'title', 
          widget: 'string',
          required: true,
        }
  - name: 'pages'
    label: 'Pages'
    label_singular: 'Page'
    editor:
      preview: false
    files:
      - label: 'Homepage'
        name: 'home'
        slug: '{{slug}}'
        file: 'content/home.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string', default: 'Welcome' }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'home' }
          - { label: 'Avatar', name: 'avatar', allow_multiple: false, widget: 'image' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'CV'
        name: 'cv'
        slug: '{{slug}}'
        identifier_field: 'name'
        file: 'content/cv.md'
        fields:
          - { label: 'Name', name: 'name', widget: 'hidden', default: 'Emil Smith' }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'cv' }
          - { label: 'Intro', name: 'intro', widget: 'markdown' }             
          - { label: 'Phone', name: 'phone', widget: 'number' }         
          - { label: 'Email', name: 'email', widget: 'string' }  
          - { label: 'Skills', name: 'skills', widget: 'list', allow_multiple: true, 
              field: { label: 'Skill', name: skill, widget: 'string'} 
            }    
          - { label: 'Jobs',
              name: 'jobs',
              label_singular: 'Job',
              widget: 'list',
              fields: [
                { label: 'Title', name: 'title', widget: 'string'},
                { label: 'Company', name: 'company', widget: 'string'},
                { label: 'Start Year', name: 'startYear', widget: 'number', min: 2009, default: 2020},
                { label: 'End Year', name: 'endYear', widget: 'number', required: false, min: 2009, default: 2020},
                { label: 'Description', name: 'description', widget: 'markdown'}
              ]
            }
          - { label: 'Outro', name: 'outro', widget: 'markdown' }
  - name: 'details'
    label: 'Details'
    editor:
      preview: false
    files: [
      {
        name: 'contact',
        label: 'Contact',
        file: 'content/contact.md',
        fields: [
          {label: 'Title', name: 'title', default: 'Contact Details', widget: 'string'},
          {label: 'Email', name: 'email', widget: 'string'},
          {label: 'Phone', name: 'phone', widget: 'number', default: 07503111160},
          {
            label: 'Social Links', 
            label_singular: 'Social Link',
            name: 'socialLinks', 
            widget: 'list',
            fields: [
              {label: 'url', name: 'url', widget: 'string'}
            ]
          }
        ]
      }
    ]