backend:
  name: git-gateway
  branch: netlify # Branch to update (optional; defaults to master)

local_backend: true

media_folder: static/img
public_folder: /img

media_library: {
  name: uploadcare,
  config: {
    publicKey: 7bbbca05c21a8452097d
  }
}

collections:
  - name: 'articles'
    label: 'Articles'
    label_singular: 'Article'
    folder: 'content/articles'
    format: 'frontmatter'
    sort: 'date:desc'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Hero', name: 'hero', allow_multiple: false, widget: 'image' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Meta Description', name: 'meta_description', widget: 'string'}
      - { 
          label: 'Gallery One', 
          name: 'gallery', 
          allow_multiple: true, 
          optional: true,
          widget: 'image', 
          media_library: {
            config: {multiple: true}
          }
        }
      - { label: 'Body One', name: 'body', widget: 'markdown' }
      - { 
          label: 'Gallery Two', 
          name: 'gallery-2', 
          allow_multiple: true, 
          optional: true,
          widget: 'image', 
          media_library: {
            config: {multiple: true}
          }
        }
      - { label: 'Body Two', name: 'body-2', widget: 'markdown' }
      - { label: 'Tags',
          name: 'tags',
          widget: 'relation',
          collection: 'tags',
          folder: 'content/_tags/',
          display_fields: [title],
          search_fields: [title],
          value_field: 'title',
          multiple: true
        }
  - name: 'case-studies'
    label: 'Case Studies'
    label_singular: 'Case Study'
    folder: 'content/case-studies'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Hero', name: 'hero', allow_multiple: false, widget: 'image' }
      - { label: 'Label', name: 'label', widget: 'string'}
      - { label: 'Publish Date', name: 'date', widget: 'datetime', format: 'YYYY' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Meta Description', name: 'meta_description', widget: 'string'}
      - { label: 'Summary', name: 'summary', widget: 'markdown', optional: true }
      - { 
          label: 'Gallery', 
          name: 'gallery', 
          allow_multiple: true, 
          optional: true,
          widget: 'image', 
          media_library: {
            config: {multiple: true}
          }
        }
      - { label: 'Background', name: 'background', widget: 'markdown', optional: true }
      - { 
          label: 'Gallery', 
          name: 'gallery-2', 
          allow_multiple: true, 
          optional: true,
          widget: 'image', 
          media_library: {
            config: {multiple: true}
          }
        }
      - { label: 'Goals', name: 'goals', widget: 'markdown', optional: true }
      - { 
          label: 'Gallery', 
          name: 'gallery-3', 
          allow_multiple: true, 
          optional: true,
          widget: 'image', 
          media_library: {
            config: {multiple: true}
          }
        }
      - { label: 'Method', name: 'method', widget: 'markdown', optional: true }
      - { 
          label: 'Gallery', 
          name: 'gallery-4', 
          allow_multiple: true, 
          optional: true,
          widget: 'image', 
          media_library: {
            config: {multiple: true}
          }
        }
      - { label: 'Results', name: 'results', widget: 'markdown', optional: true }
      - { 
          label: 'Gallery', 
          name: 'gallery-5', 
          allow_multiple: true, 
          optional: true,
          widget: 'image', 
          media_library: {
            config: {multiple: true}
          }
        }
      - { label: 'Wrap Up', name: 'wrap-up', widget: 'markdown', optional: true }
  - name: 'tags'
    label: 'Tags'
    label_singular: 'Tag'
    folder: 'content/tags/'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { 
          label: 'Title', 
          name: 'title', 
          widget: 'string',
          required: true,
        }
  - name: 'jobs'
    label: 'Jobs'
    label_singular: 'Job'
    folder: 'content/_jobs/'
    identifier_field: job
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string'}
      - { label: 'Company', name: 'company', widget: 'string'}
      - { label: 'Start Year', name: 'start-year', widget: 'date', format: 'YYYY'}
      - { label: 'End Year', name: 'end-year', widget: 'date', format: 'YYYY'}
      - { label: 'Description', name: 'description', widget: 'string'}
  - name: 'pages'
    label: 'Pages'
    label_singular: 'Page'
    editor:
      preview: false
    files:
      - label: 'Homepage'
        name: 'home'
        file: 'content/home.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string', default: 'Welcome' }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'home' }
          - { label: 'Avatar', name: 'avatar', allow_multiple: false, widget: 'image' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'CV'
        name: 'cv'
        file: 'content/cv.md'
        fields:
          - { label: 'Name', name: 'name', widget: 'hidden', default: 'Emil Smith' }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'cv' }
          - { label: 'Intro', name: 'intro', widget: 'markdown' }      
          - { label: 'Outro', name: 'outro', widget: 'markdown' }       
          - { label: 'Phone', name: 'phone', widget: 'number' }         
          - { label: 'Email', name: 'email', widget: 'string' }      
          - { label: 'Jobs',
              name: 'jobs',
              label_singular: 'Job',
              widget: 'relation',
              collection: 'jobs',
              display_fields: [title, company, start-year, end-year, description],
              search_fields: [title, company, start-year, end-year, description],
              value_field: 'title',
            }